apiVersion: v1
kind: Service
metadata:
  name: productpage-svc
  namespace: cdps-27
  labels:
    app: productpage
spec:
  type: LoadBalancer
  ports:
  - port: 9080
    targetPort: 9080
  selector:
    app: productpage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage
  namespace: cdps-27
  labels:
    app: productpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
  template:
    metadata:
      labels:
        app: productpage
    spec:
      containers:
      - name: productpage
        image: 27/productpage
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
